In [1]:
import pandas as pd

In [2]:
air_quality_no2 = pd.read_csv("data/air_quality_no2_long.csv",
                              parse_dates=True)

In [3]:
air_quality_no2.head()

    city country                   date.utc location parameter  value   unit
0  Paris      FR  2019-06-21 00:00:00+00:00  FR04014       no2   20.0  µg/m³
1  Paris      FR  2019-06-20 23:00:00+00:00  FR04014       no2   21.8  µg/m³
2  Paris      FR  2019-06-20 22:00:00+00:00  FR04014       no2   26.5  µg/m³
3  Paris      FR  2019-06-20 21:00:00+00:00  FR04014       no2   24.9  µg/m³
4  Paris      FR  2019-06-20 20:00:00+00:00  FR04014       no2   21.4  µg/m³

In [6]:
air_quality_no2 = air_quality_no2[["date.utc","location","parameter","value"]]

In [7]:
air_quality_no2.head()

                    date.utc location parameter  value
0  2019-06-21 00:00:00+00:00  FR04014       no2   20.0
1  2019-06-20 23:00:00+00:00  FR04014       no2   21.8
2  2019-06-20 22:00:00+00:00  FR04014       no2   26.5
3  2019-06-20 21:00:00+00:00  FR04014       no2   24.9
4  2019-06-20 20:00:00+00:00  FR04014       no2   21.4

In [8]:
air_quality_pm25 = pd.read_csv("data/air_quality_pm25_long.csv")

In [9]:
air_quality_pm25.head()

,city,country,date.utc,location,parameter,value,unit
0,Antwerpen,BE,2019-06-18 06:00:00+00:00,BETR801,pm25,18.0,µg/m³
1,Antwerpen,BE,2019-06-17 08:00:00+00:00,BETR801,pm25,6.5,µg/m³
2,Antwerpen,BE,2019-06-17 07:00:00+00:00,BETR801,pm25,18.5,µg/m³
3,Antwerpen,BE,2019-06-17 06:00:00+00:00,BETR801,pm25,16.0,µg/m³
4,Antwerpen,BE,2019-06-17 05:00:00+00:00,BETR801,pm25,7.5,µg/m³

In [12]:
air_quality_pm25 = air_quality_pm25[["date.utc","location","parameter","value"]]

In [13]:
air_quality_pm25.head()

                    date.utc location parameter  value
0  2019-06-18 06:00:00+00:00  BETR801      pm25   18.0
1  2019-06-17 08:00:00+00:00  BETR801      pm25    6.5
2  2019-06-17 07:00:00+00:00  BETR801      pm25   18.5
3  2019-06-17 06:00:00+00:00  BETR801      pm25   16.0
4  2019-06-17 05:00:00+00:00  BETR801      pm25    7.5

In [14]:
#combine the measurements of 𝑁⁢𝑂2 and 𝑃⁢𝑀25 ,combine the measurements of 𝑁⁢𝑂2 and p⁢𝑀25

In [17]:
air_quality = pd.concat([air_quality_pm25,air_quality_no2],axis = 0)

In [18]:
air_quality.head()

                    date.utc location parameter  value
0  2019-06-18 06:00:00+00:00  BETR801      pm25   18.0
1  2019-06-17 08:00:00+00:00  BETR801      pm25    6.5
2  2019-06-17 07:00:00+00:00  BETR801      pm25   18.5
3  2019-06-17 06:00:00+00:00  BETR801      pm25   16.0
4  2019-06-17 05:00:00+00:00  BETR801      pm25    7.5

In [19]:
#By default concatenation is along axis 0, so the resulting table combines the rows of the input tables.

In [23]:
print("Shape of the air_quality_pm25 table:",air_quality_pm25.shape)

Shape of the air_quality_pm25 table: (1110, 4)

In [24]:
print("Shape of the air_quality_no2 table:",air_quality_no2.shape)

Shape of the air_quality_no2 table: (2068, 4)

In [25]:
print('Shape of the resulting ``air_quality`` table: ', air_quality.shape)

Shape of the resulting ``air_quality`` table:  (3178, 4)

In [26]:
#Most operations like concatenation or summary statistics are by default across rows (axis 0)

In [28]:
air_quality = air_quality.sort_values("date.utc")
air_quality.head()

                       date.utc            location parameter  value
2067  2019-05-07 01:00:00+00:00  London Westminster       no2   23.0
1003  2019-05-07 01:00:00+00:00             FR04014       no2   25.0
100   2019-05-07 01:00:00+00:00             BETR801      pm25   12.5
1098  2019-05-07 01:00:00+00:00             BETR801       no2   50.5
1109  2019-05-07 01:00:00+00:00  London Westminster      pm25    8.0

In [30]:
#The concatfunction provides a convenient solution with the keys argument, adding an additional (hierarchical) row index

In [31]:
air_quality = pd.concat([air_quality_pm25, air_quality_no2],keys= ["PM25","no2"])

In [34]:
air_quality[:20]

                          date.utc location parameter  value
PM25 0   2019-06-18 06:00:00+00:00  BETR801      pm25   18.0
     1   2019-06-17 08:00:00+00:00  BETR801      pm25    6.5
     2   2019-06-17 07:00:00+00:00  BETR801      pm25   18.5
     3   2019-06-17 06:00:00+00:00  BETR801      pm25   16.0
     4   2019-06-17 05:00:00+00:00  BETR801      pm25    7.5
     5   2019-06-17 04:00:00+00:00  BETR801      pm25    7.5
     6   2019-06-17 03:00:00+00:00  BETR801      pm25    7.0
     7   2019-06-17 02:00:00+00:00  BETR801      pm25    7.0
     8   2019-06-17 01:00:00+00:00  BETR801      pm25    8.0
     9   2019-06-16 01:00:00+00:00  BETR801      pm25   15.0
     10  2019-06-15 01:00:00+00:00  BETR801      pm25   11.0
     11  2019-06-14 09:00:00+00:00  BETR801      pm25   12.0
     12  2019-06-13 01:00:00+00:00  BETR801      pm25    3.0
     13  2019-06-12 01:00:00+00:00  BETR801      pm25   16.0
     14  2019-06-11 01:00:00+00:00  BETR801      pm25    3.5
     15  2019-06-10 01:00:00+00:00  BETR801      pm25    8.5
     16  2019-06-09 01:00:00+00:00  BETR801      pm25    6.0
     17  2019-06-08 01:00:00+00:00  BETR801      pm25    6.5
     18  2019-06-06 01:00:00+00:00  BETR801      pm25    6.5
     19  2019-06-05 01:00:00+00:00  BETR801      pm25   11.0

In [36]:
air_quality.tail()

                           date.utc            location parameter  value
no2 2063  2019-05-07 06:00:00+00:00  London Westminster       no2   26.0
    2064  2019-05-07 04:00:00+00:00  London Westminster       no2   16.0
    2065  2019-05-07 03:00:00+00:00  London Westminster       no2   19.0
    2066  2019-05-07 02:00:00+00:00  London Westminster       no2   19.0
    2067  2019-05-07 01:00:00+00:00  London Westminster       no2   23.0

In [38]:
#The existence of multiple row/column indices at the same time has not been mentioned within these tutorials. 
#Hierarchical indexing or MultiIndex is an advanced and powerful pandas feature to analyze higher dimensional data.
#Multi-indexing is out of scope for this pandas introduction. For the moment, 
#remember that the function reset_index can be used to convert any level of an index to a column, e.g. air_quality.reset_index(level=0)

In [42]:
##Join tables using a common identifier

In [43]:
#Add the station coordinates, provided by the stations metadata table, to the corresponding rows in the measurements table.

In [40]:
station_coord = pd.read_csv("data/air_quality_stations.csv")

In [41]:
station_coord.head()

  location  coordinates.latitude  coordinates.longitude
0  BELAL01              51.23619                4.38522
1  BELHB23              51.17030                4.34100
2  BELLD01              51.10998                5.00486
3  BELLD02              51.12038                5.02155
4  BELR833              51.32766                4.36226

In [44]:
air_quality.head()

                         date.utc location parameter  value
PM25 0  2019-06-18 06:00:00+00:00  BETR801      pm25   18.0
     1  2019-06-17 08:00:00+00:00  BETR801      pm25    6.5
     2  2019-06-17 07:00:00+00:00  BETR801      pm25   18.5
     3  2019-06-17 06:00:00+00:00  BETR801      pm25   16.0
     4  2019-06-17 05:00:00+00:00  BETR801      pm25    7.5

In [46]:
air_quality = pd.merge(air_quality , station_coord , how = "left", on = "location")

In [47]:
air_quality.head()

,date.utc,location,parameter,value,coordinates.latitude,coordinates.longitude
0,2019-06-18 06:00:00+00:00,BETR801,pm25,18.0,51.20966,4.43182
1,2019-06-17 08:00:00+00:00,BETR801,pm25,6.5,51.20966,4.43182
2,2019-06-17 07:00:00+00:00,BETR801,pm25,18.5,51.20966,4.43182
3,2019-06-17 06:00:00+00:00,BETR801,pm25,16.0,51.20966,4.43182
4,2019-06-17 05:00:00+00:00,BETR801,pm25,7.5,51.20966,4.43182

In [ ]:
#Using the merge() function, for each of the rows in the air_quality table, the corresponding coordinates are added from the 
#air_quality_stations_coord table. Both tables have the column location in common which is used as a key to combine the information.
#By choosing the left join, only the locations available in the air_quality (left) table, i.e.
#FR04014, BETR801 and London Westminster, end up in the resulting table.

In [48]:
#Add the parameters’ full description and name, provided by the parameters metadata table, to the measurements table???

In [49]:
air_quality_parameters = pd.read_csv("data/air_quality_parameters.csv")

In [51]:
air_quality_parameters.head()

     id                                        description  name
0    bc                                       Black Carbon    BC
1    co                                    Carbon Monoxide    CO
2   no2                                   Nitrogen Dioxide   NO2
3    o3                                              Ozone    O3
4  pm10  Particulate matter less than 10 micrometers in...  PM10

In [52]:
air_quality = pd.merge(air_quality,air_quality_parameters,how= "left",left_on= "parameter",right_on="id")

In [53]:
air_quality.head()

,date.utc,location,parameter,value,coordinates.latitude,coordinates.longitude,id,description,name
0,2019-06-18 06:00:00+00:00,BETR801,pm25,18.0,51.20966,4.43182,pm25,Particulate matter less than 2.5 micrometers i...,PM2.5
1,2019-06-17 08:00:00+00:00,BETR801,pm25,6.5,51.20966,4.43182,pm25,Particulate matter less than 2.5 micrometers i...,PM2.5
2,2019-06-17 07:00:00+00:00,BETR801,pm25,18.5,51.20966,4.43182,pm25,Particulate matter less than 2.5 micrometers i...,PM2.5
3,2019-06-17 06:00:00+00:00,BETR801,pm25,16.0,51.20966,4.43182,pm25,Particulate matter less than 2.5 micrometers i...,PM2.5
4,2019-06-17 05:00:00+00:00,BETR801,pm25,7.5,51.20966,4.43182,pm25,Particulate matter less than 2.5 micrometers i...,PM2.5

In [54]:
#For database-like merging/joining of tables, use the merge function.

In [55]:
#Multiple tables can be concatenated column-wise or row-wise using the concat function.