In [2]:
import pandas as pd

In [4]:
#here we store the data of csv in a variable called titanic
titanic = pd.read_csv('data/titanic.csv')

In [6]:
titanic.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [7]:
#strings are referred to as objects in pandas. The object data type is a catch-all for columns that contain any kind of Python object.
#dtypes is an attribute of a DataFrame and Series , they dont need paranthesis to be called. It returns a Series with the data type of each column in the DataFrame.

In [8]:
#for data in excel 
In [6]: titanic.to_excel("titanic.xlsx", sheet_name="passengers", index=False)

ModuleNotFoundError: No module named 'openpyxl'

In [9]:
In [7]: titanic = pd.read_excel("titanic.xlsx", sheet_name="passengers")

FileNotFoundError: [Errno 2] No such file or directory: 'titanic.xlsx'

In [10]:
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [ ]:
#manupulation of data in pandas is done using the DataFrame and Series objects. A DataFrame is a 2-dimensional labeled data structure with columns of potentially different types. A Series is a one-dimensional labeled array capable of holding any data type.

In [14]:

#how to select a specific column in a DataFrame

ages = titanic["Age"]
print(ages)

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [15]:
type(ages)

pandas.Series

In [ ]:
titanic["Age"].shape
#kinda tells the shape of the matrix and all

(891,)

In [18]:
#select multiple columns in a dataframe 
age_sex = titanic[["Age","Sex"]]

In [19]:
print(age_sex)

      Age     Sex
0    22.0    male
1    38.0  female
2    26.0  female
3    35.0  female
4    35.0    male
..    ...     ...
886  27.0    male
887  19.0  female
888   NaN  female
889  26.0    male
890  32.0    male

[891 rows x 2 columns]

In [20]:
age_sex.shape

(891, 2)

In [21]:
#how to filter specific rows in a DataFrame
above_35 = titanic[titanic["Age"]>35]

In [26]:
above_35.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S

In [27]:
above_35.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.0,0,0,236852,13.0000,NaN,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q

In [28]:
above_35.shape

(217, 12)

In [29]:
len(titanic)

891

In [30]:
#interested in the Titanic passengers from cabin class 2 and 3.
class_23 = titanic[titanic["Pclass"].isin([2, 3])]
class_23.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [31]:
#, the isin() conditional function returns a True for each row the values are in the provided list

In [ ]:
class_23 = titanic[(titanic["Pclass"] == 2) | (titanic["Pclass"] == 3)]

class_23.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [35]:
#When combining multiple conditional statements, each condition must be surrounded by parentheses (). Moreover, you can not use or/and but need to use the or operator | and the and operator &.

In [38]:
age_no_na = titanic[titanic["Age"].notna()]
#The notna() conditional function returns a True for each row the values are not a Null

In [39]:
age_no_na.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [40]:
#iloc/loc are used to select rows and columns in a DataFrame. The difference between the two is that iloc uses integer-based indexing, 
# while loc uses label-based indexing.

In [42]:
#I’m interested in rows 10 till 25 and columns 3 to 5.
titanic.iloc[10:25 , 3 :5]

                                                 Name     Sex
10                     Sandstrom, Miss Marguerite Rut  female
11                            Bonnell, Miss Elizabeth  female
12                     Saundercock, Mr. William Henry    male
13                        Andersson, Mr. Anders Johan    male
14                Vestrom, Miss Hulda Amanda Adolfina  female
15                   Hewlett, Mrs. (Mary D Kingcome)   female
16                                Rice, Master Eugene    male
17                       Williams, Mr. Charles Eugene    male
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female
19                            Masselmani, Mrs. Fatima  female
20                               Fynney, Mr. Joseph J    male
21                              Beesley, Mr. Lawrence    male
22                         McGowan, Miss Anna "Annie"  female
23                       Sloper, Mr. William Thompson    male
24                       Palsson, Miss Torborg Danira  female

In [43]:
#after selecthing the shit we can just ykk change the values 
titanic.iloc[0:3 , 3] = "anonymus"

In [46]:
print(titanic.iloc[2, 3])

anonymus