In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
air_quality = pd.read_csv("data/air_quality_no2_long.csv")

In [5]:
air_quality = air_quality.rename(columns = {"date.utc":"datetime"})

In [6]:
air_quality.head()

    city country                   datetime location parameter  value   unit
0  Paris      FR  2019-06-21 00:00:00+00:00  FR04014       no2   20.0  µg/m³
1  Paris      FR  2019-06-20 23:00:00+00:00  FR04014       no2   21.8  µg/m³
2  Paris      FR  2019-06-20 22:00:00+00:00  FR04014       no2   26.5  µg/m³
3  Paris      FR  2019-06-20 21:00:00+00:00  FR04014       no2   24.9  µg/m³
4  Paris      FR  2019-06-20 20:00:00+00:00  FR04014       no2   21.4  µg/m³

In [7]:
air_quality.city.unique()

<StringArray>
['Paris', 'Antwerpen', 'London']
Length: 3, dtype: str

In [8]:
#How to handle time series data with ease

In [9]:
#1 Using pandas datetime properties

In [10]:
air_quality["datetime"] = pd.to_datetime(air_quality["datetime"])

In [11]:
air_quality["datetime"]

0      2019-06-21 00:00:00+00:00
1      2019-06-20 23:00:00+00:00
2      2019-06-20 22:00:00+00:00
3      2019-06-20 21:00:00+00:00
4      2019-06-20 20:00:00+00:00
                  ...
2063   2019-05-07 06:00:00+00:00
2064   2019-05-07 04:00:00+00:00
2065   2019-05-07 03:00:00+00:00
2066   2019-05-07 02:00:00+00:00
2067   2019-05-07 01:00:00+00:00
Name: datetime, Length: 2068, dtype: datetime64[us, UTC]

In [12]:
#As many data sets do contain datetime information in one of the columns, 
#pandas input function like pandas.read_csv() and pandas.read_json() can do the transformation to dates 
#when reading the data using the parse_dates parameter with a list of the columns to read as Timestamp:

In [19]:
air_quality1 = pd.read_csv("data/air_quality_no2_long.csv" ,parse_dates = ["date.utc"])

In [20]:
#What is the start and end date of the time series data set we are working with?

In [22]:
air_quality["datetime"].min()

Timestamp('2019-05-07 01:00:00+0000', tz='UTC')

In [23]:
air_quality["datetime"].max()

Timestamp('2019-06-21 00:00:00+0000', tz='UTC')

In [24]:
air_quality["datetime"].max() - air_quality["datetime"].min()

Timedelta('44 days 23:00:00')

In [27]:
#i want to add a new column to the DataFrame containing only the month of the measurement

In [25]:
air_quality["month"] = air_quality["datetime"].dt.month
air_quality.head()

,city,country,datetime,location,parameter,value,unit,month
0,Paris,FR,2019-06-21 00:00:00+00:00,FR04014,no2,20.0,µg/m³,6
1,Paris,FR,2019-06-20 23:00:00+00:00,FR04014,no2,21.8,µg/m³,6
2,Paris,FR,2019-06-20 22:00:00+00:00,FR04014,no2,26.5,µg/m³,6
3,Paris,FR,2019-06-20 21:00:00+00:00,FR04014,no2,24.9,µg/m³,6
4,Paris,FR,2019-06-20 20:00:00+00:00,FR04014,no2,21.4,µg/m³,6

In [28]:
#By using Timestamp objects for dates, a lot of time-related properties are provided by pandas. 
#For example the month, but also year, quarter,… All of these properties are accessible by the dt accessor.