In [2]:
import pandas as pd 
import numpy as np

In [3]:
air_quality = pd.read_csv("data/pan.csv")

In [4]:
#To create a new column, use the square brackets [] with the new column name 
# at the left side of the assignment.

In [5]:
air_quality["NO2 concentration"] = air_quality["station_london"]*1.82

In [6]:
air_quality.head()

,datetime,station_antwerp,station_paris,station_london,NO2 concentration
0,2019-05-07 02:00:00,NaN,NaN,23.0,41.86
1,2019-05-07 03:00:00,50.5,25.0,19.0,34.58
2,2019-05-07 04:00:00,45.0,27.7,19.0,34.58
3,2019-05-07 05:00:00,NaN,50.4,16.0,29.12
4,2019-05-07 06:00:00,NaN,61.9,NaN,NaN

In [7]:
# You do not need to use a loop to iterate each of the rows

In [8]:
#check the ratios in paris and antwerp

In [9]:
air_quality["ratio_paris_antwerp"] =air_quality["station_paris"]/air_quality["station_antwerp"]

In [10]:
air_quality.head()

,datetime,station_antwerp,station_paris,station_london,NO2 concentration,ratio_paris_antwerp
0,2019-05-07 02:00:00,NaN,NaN,23.0,41.86,NaN
1,2019-05-07 03:00:00,50.5,25.0,19.0,34.58,0.495050
2,2019-05-07 04:00:00,45.0,27.7,19.0,34.58,0.615556
3,2019-05-07 05:00:00,NaN,50.4,16.0,29.12,NaN
4,2019-05-07 06:00:00,NaN,61.9,NaN,NaN,NaN

In [11]:
#Other mathematical operators (+, -, *, /, …) and logical operators (<, >, ==, …) also work element-wise.

In [12]:
#apply () method to apply a function along an axis of the DataFrame.
df = pd.DataFrame([[4, 9]] * 3, columns=["A", "B"])

In [13]:
df

   A  B
0  4  9
1  4  9
2  4  9

In [14]:
df.apply(np.sqrt)

     A    B
0  2.0  3.0
1  2.0  3.0
2  2.0  3.0

In [15]:
#rename the data columns

In [16]:
air_quality_renamed = air_quality.rename(
    columns = {
        "station_london": "BETR801",
        "station_paris": "FR04014",
        "station_antwerp": "London Westminster"
    }
)

In [17]:
air_quality_renamed.head()

,datetime,London Westminster,FR04014,BETR801,NO2 concentration,ratio_paris_antwerp
0,2019-05-07 02:00:00,NaN,NaN,23.0,41.86,NaN
1,2019-05-07 03:00:00,50.5,25.0,19.0,34.58,0.495050
2,2019-05-07 04:00:00,45.0,27.7,19.0,34.58,0.615556
3,2019-05-07 05:00:00,NaN,50.4,16.0,29.12,NaN
4,2019-05-07 06:00:00,NaN,61.9,NaN,NaN,NaN

In [ ]:
#The rename() function can be used for both row labels and column labels. 
# Provide a dictionary with the keys the current names and the values the new names to update the corresponding names.

In [20]:
air_quality_renamed = air_quality_renamed.rename(columns=str.lower)

In [21]:
air_quality_renamed.head()

,datetime,london westminster,fr04014,betr801,no2 concentration,ratio_paris_antwerp
0,2019-05-07 02:00:00,NaN,NaN,23.0,41.86,NaN
1,2019-05-07 03:00:00,50.5,25.0,19.0,34.58,0.495050
2,2019-05-07 04:00:00,45.0,27.7,19.0,34.58,0.615556
3,2019-05-07 05:00:00,NaN,50.4,16.0,29.12,NaN
4,2019-05-07 06:00:00,NaN,61.9,NaN,NaN,NaN

In [ ]:
#well we end it here now